[theme]
primaryColor = "#0f3460"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#1a1d23"
font = "sans serif"

[client]
toolbarMode = "minimal"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
runOnSave = true

[client]
showErrorDetails = false

[cache]
maxEntries = 1000
ttlSeconds = 3600
